version: '3'

services:
  # MySQL
  db_mysql8:
    container_name: mysql_spring_auth
    restart: 'always'
    image: mysql:8.0.31
    command: mysqld --default-authentication-plugin=mysql_native_password --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: auth
    ports:
      - '3306:3306'

volumes:
  db_data: { }