version: '3'

services:
  db-postgres:
    container_name: postgre_spring_auth
    restart: 'always'
    image: postgres
    volumes:
      - ./docker/sql/01-user.sql:/docker-entrypoint-initdb.d/01-user.sql
    environment:
      POSTGRES_USER: "root"
      POSTGRES_PASSWORD: "123456"
      POSTGRES_DB: "auth"
    ports:
      - "5432:5432"

volumes:
  db_data: { }